// <auto-generated />
using System;
using EFCoreSample.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCoreSample.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.Alphabet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Characters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alphabets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Characters = "abcdefghijklmnopqrstuvwxyz",
                            Script = "latin"
                        },
                        new
                        {
                            Id = 2L,
                            Characters = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя",
                            Script = "cyrillic"
                        });
                });

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.CharacterOnGrid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlphabetId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DataGridId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlphabetId");

                    b.HasIndex("DataGridId");

                    b.ToTable("CharactersOnGrid");
                });

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.DataGrid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataGrids");
                });

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.Direction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ColumnMovement")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowMovement")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.WordOnGrid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("DataGridId")
                        .HasColumnType("bigint");

                    b.Property<long>("DirectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WordSetId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataGridId");

                    b.HasIndex("DirectionId");

                    b.HasIndex("WordSetId");

                    b.ToTable("WordsOnGrid");
                });

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.WordSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Words")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WordSets");
                });

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.CharacterOnGrid", b =>
                {
                    b.HasOne("EFCoreSample.Persistence.Entities.Alphabet", "Alphabet")
                        .WithMany()
                        .HasForeignKey("AlphabetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreSample.Persistence.Entities.DataGrid", null)
                        .WithMany("CharacterOnGrids")
                        .HasForeignKey("DataGridId");

                    b.Navigation("Alphabet");
                });

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.WordOnGrid", b =>
                {
                    b.HasOne("EFCoreSample.Persistence.Entities.DataGrid", null)
                        .WithMany("WordOnGrids")
                        .HasForeignKey("DataGridId");

                    b.HasOne("EFCoreSample.Persistence.Entities.Direction", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreSample.Persistence.Entities.WordSet", "WordSet")
                        .WithMany()
                        .HasForeignKey("WordSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");

                    b.Navigation("WordSet");
                });

            modelBuilder.Entity("EFCoreSample.Persistence.Entities.DataGrid", b =>
                {
                    b.Navigation("CharacterOnGrids");

                    b.Navigation("WordOnGrids");
                });
#pragma warning restore 612, 618
        }
    }
}
